---
title: "Check transfer completeness in the qPortal"
output: html_notebook
author: "Andrea Borbon-Garcia"
date: "2025-10-29"
---


```{r}
library(readr)
library(dplyr)
library(stringr)
```

```{r}

transfer_date = "20251027"

qportal_report_filepath = "../data_transfer_checkup/NCCT_VOOLSTRA_Q2181_Raw_Data_.tsv"
  
demultiplexed_files_filepath = "Z:/2307-Voolstra/ITS_16s/Batch7/16S/16S_standard/251027_results-demultiplex-16Sstandard/M45K6/NA/demultiplexed_files.txt"

```


```{r}


checkup_transfer = function(qportal_report_filepath, demultiplexed_files_filepath,transfer_date) {

  #load libraries
  library(readr)
  library(dplyr)
  library(stringr)  
  
  #Import files and rename columns
  qportal_report = suppressMessages(
    read_tsv(qportal_report_filepath)
  )
  
  demultiplexed_files = suppressMessages(
    read_tsv(demultiplexed_files_filepath,col_names = "ncct_filename")
  )
  
  #filter files by transfer date and create a column with the ncct filename
  transfer_qportal = qportal_report %>%
                  filter(str_detect(name, paste0("_",target_date,"\\d{6}_"))) %>%
                  mutate(ncct_filename = str_remove(name, "_\\d{14}_"))
  
  #Get the total of files in each location
  n_files_ncct = nrow(demultiplexed_files)
  n_files_qportal = nrow(transfer_qportal)
  
  #Print a message with the total files in ncct and qPortal
  message(n_files_ncct," files are present in the source folder at NCCT")
  message(n_files_qportal, " files are successfully transferred to the qPortal")
  
  #Find missing samples in the qPortal (only present in ncct demultiplex results)
  missing_samples = setdiff(demultiplexed_files$ncct_filename, transfer_qportal$ncct_filename)
  total_samples = length(intersect(demultiplexed_files$ncct_filename, transfer_qportal$ncct_filename))
  
  #Print message
  if(length(missing_samples)==0){
    message("✅  All ", total_samples, " files for transfer date ",transfer_date," are present in the qPortal")}
  else{
    message("⚠️  Only", total_samples, "were transferred to the qPortal. The following files are missing in the qPortal for transfer date",transfer_date,":")
    print(missing_samples)
    
  }

}

    
 
```

```{r}
checkup_transfer(qportal_report_filepath,demultiplexed_files_filepath,transfer_date)
```

